## Copyright © 2023, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deploy LLMs to Oracle Cloud Infrastructure Compute instances"
stackDescription: "Deploy LLMs to Oracle Cloud Infrastructure Compute instances"
schemaVersion: 1.1.0
version: "20220422"
locale: "en"

variableGroups:
  - title: General Configuration
    visible: false
    variables:
      - tenancy_ocid
      - region
      - release

  - title: Required Configuration
    visible: true
    variables:
      - llm_tool
      - llm_fooocus_model
      - llm_fastchat_model
      - display_name
      - compartment_ocid

  - title: Placement
    visible: true
    variables:
      - availability_domain_name

  - title: Image and shape
    visible: true
    variables:
      #      - instance_image_ocid
      - instance_shape

  - title: Primary VNIC information
    visible: true
    variables:
      - vcn_ocid
      - subnet_ocid

  - title: Add SSH keys
    visible: true
    variables:
      - ssh_public_key

  - title: Boot volume
    visible: true
    variables:
      - bv_size

variables:
  region:
    type: oci:identity:region:name
    required: true
    visible: true
    title: "Region"
    description: "Choose region where you want to deploy the resources defined by this stack."

  llm_tool:
    type: enum
    required: true
    title: "LLM Tool"
    enum:
      - "Fooocus"
      - "FastChat"
      - "Text generation web UI"
    default: "Fooocus"

  llm_fooocus_model:
    type: enum
    required: true
    title: "LLM Model"
    enum:
      - "Stable Diffusion"
    default: "Stable Diffusion"
    visible:
      and:
        - eq:
            - llm_tool
            - "Fooocus"

  llm_fastchat_model:
    type: enum
    required: true
    title: "LLM Model"
    enum:
#      - "lmsys/vicuna-7b-v1.5"
      - "lmsys/vicuna-7b-v1.5-16k"
      - "lmsys/longchat-7b-v1.5-32k"
      - "HuggingFaceH4/zephyr-7b-beta"
      - "Xwin-LM/Xwin-LM-7B-V0.2"
#      - "lmsys/vicuna-13b-v1.5"
#      - "lmsys/vicuna-13b-v1.5-16k"
#      - "meta-llama/Llama-2-7b-chat-hf"
#      - "codellama/CodeLlama-7b-Instruct-hf"
#      - "codellama/CodeLlama-13b-Instruct-hf"
#      - "mosaicml/mpt-7b-chat"
      - "Qwen/Qwen-7B-Chat"
      - "THUDM/chatglm3-6b"
#      - "internlm/internlm-chat-7b"
    default: "lmsys/vicuna-7b-v1.5-16k"
    visible:
      and:
        - eq:
            - llm_tool
            - "FastChat"

  display_name:
    type: string
    required: true
    default: "llm-instance"
    title: "Name"

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: true
    title: "Compartment"
    description: "Choose compartment where you want to create the solution resources."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    title: "Availability domain"
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_image_ocid:
    type: oci:core:image:id
    required: true
    visible: false
    title: "Image"
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_shape:
    type: enum
    required: true
    title: "Shape"
    enum:
      - "VM.GPU.A10.1"
      - "VM.GPU.A10.2"
    default: "VM.GPU.A10.1"
    dependsOn:
      compartmentId: ${compartment_ocid}
  #      imageId: ${instance_image_ocid}


  vcn_ocid:
    type: oci:core:vcn:id
    required: true
    visible: true
    title: "VCN"
    dependsOn:
      compartmentId: ${compartment_ocid}

  subnet_ocid:
    type: oci:core:subnet:id
    required: true
    visible: true
    title: "Subnet"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${vcn_ocid}

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: true
    title: "Public SSH Key"
    description: "Upload a public key that you already have."

  bv_size:
    type: number
    required: true
    minimum: 50
    maximum: 32768
    multipleOf: 1
    default: 200
    title: "Boot volume size (GB)"
